name: Build Docker images

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: true
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to GitHub container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push all images
      run: IMAGE_SUFFIX=${GITHUB_SHA} make push-all
      env:
        PLATFORM: ${{ matrix.platform }}
